### ISSUE TITLE
At home testing request

### ISSUE THREAD

**Issue by avi33tbtt** [sencode/covenant#1]
FDA allowed at home sample collection and testing in usa and now it have also started in india, can be an important feature to have?

https://www.fda.gov/news-events/press-announcements/coronavirus-covid-19-update-fda-authorizes-first-standalone-home-sample-collection-kit-can-be-used

https://www.fda.gov/news-events/press-announcements/coronavirus-covid-19-update-fda-takes-steps-streamline-development-tests-home-sample-collection

"COVID-19 Test Home Sample Collection Booking Form (Bangalore city limits only)
RT-PCR Tests home sample collection service of nasal/throat swab offered by Shree Polyclinic & Lab (Dr Chitra) in collaboration with Apollo Hospitals, Bannerghatta Road. Available in Bangalore City limits only." ref- 
https://docs.google.com/forms/d/e/1FAIpQLSeC3YRilv6BUKb-9kjjhkaVNZRh5aZ0pWtVAwCV67U-tSyKfg/viewform?vc=0&c=0&w=1

**Comment by sencode** [comment]
Home testing is part of our use case as can be seen in the diagram on covn.org. The quarantine officer can order testing at home (if available) or at a lab based on evolving symptoms that are submitted by the patient once or twice a day.

**Comment by avi33tbtt** [comment]
Thanks, that's great!
